version: "3"
services:
  reader:
    build: .
    image: ghcr.io/chipp/lisa:latest
    expose:
      - 8080
    ports:
      - 8081:8081
    entrypoint: ["./lisa"]
    environment:
      - RUST_LOG=debug
      - VIRTUAL_HOST=lisa.burdukov.by
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=lisa.burdukov.by
      - LETSENCRYPT_EMAIL=chippcheg@gmail.com
    restart: unless-stopped
networks:
  default:
    external:
      name: nginxproxy_default
