[package]
name = "lisa"
version = "0.1.0"
authors = ["Vladimir Burdukov <chippcheg@gmail.com>"]
edition = "2018"

[dependencies]
alice = { path = "../../lib/alice" }
elisheba = { path = "../../lib/elisheba" }

pretty_env_logger = "0.4"
log = "0.4"

# TODO: full is bad
# hyper = { version = "0.14", features = ["server", "http1"] }
hyper = { version = "0.14", features = ["full"] }

tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-util", "net", "time"] }
futures = "0.3"

bytes = "1"
url = "2.0"

jsonwebtoken = "7.2"
chrono = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
# rmp-serde = "0.15.4"
